### PR TITLE
Set up GitHub Actions and GCP deployment

### PR DESCRIPTION
**Pull request by alankbi**
### List of Changes:

* Get Maven tests to run on GitHub Actions
* Add deploy step to GCP

### Notes

* The deploy step is as follows:
  * SSH into the VM instance (setup instructions in the GCP doc)
  * cd into the tester repo and run git pull
  * Kill the existing pm2 and port 8080 processes
  * Restart the service with the up-to-date tester repo code

### CODE REVIEW

**Comment by zpChris** [comment]
[Setup api calls to tester from main](https://trello.com/c/OgWH7zCO/229-setup-api-calls-to-tester-from-main)

**Review by zpChris — APPROVED** [review]
LGTM! Thanks for adding this 😃

**Comment by zpChris** [comment]
Heads up @alankbi, not sure that you saw I approved this, I think you can merge ✅

**Comment by alankbi** [comment]
> Heads up @alankbi, not sure that you saw I approved this, I think you can merge ✅

Yeah I saw the approval, thanks - however, I was actually thinking, should we hold off on merging this PR? I know that with my PR a lot of tests will be failing or unimplemented until we flesh out the design more, which means that might end up blocking other PRs from being merged. Thoughts?

**Comment by zpChris** [comment]
> Yeah I saw the approval, thanks - however, I was actually thinking, should we hold off on merging this PR? I know that with my PR a lot of tests will be failing or unimplemented until we flesh out the design more, which means that might end up blocking other PRs from being merged. Thoughts?

Yeah I don't have any problem with that, sounds good. I will say I might be hesitant to merge in failing tests, but I'll judge it on a case-by-case basis and that doesn't mean we have to merge this in.

**Comment by alankbi** [comment]
Updated this PR to get the tests to work on GitHub Actions and also add the deploy step to GCP

**Review by zpChris — APPROVED** [review]
LGTM!

I you haven't fixed the Java 11 versioning issue yet, let me know; otherwise, I think this is good to merge after #12 👍

**Comment by zpChris** [comment]
[Get tester GitHub Actions + GCP deployment working](https://trello.com/c/8FbGKIrD/269-get-tester-github-actions-gcp-deployment-working)

**Pull request merged**
